.\" @(#)lsp.1	1.3
.\" vim:ts=4:sw=4:syntax=nroff
.fp 1 R
.fp 2 I
.fp 3 B
.fp 4 BI
.fp 5 CO
.fp 6 CI
.fp 7 CB
.nr X
.TH lsp 1 "21 Apr 2007" ""
.SH NAME
lsp \- list IPv4 ports with listening processes
.SH SYNOPSIS
\f3lsp\f1 [\f3-t\f1] [\f3-x\f1] [\f3-n\f1] [\f3-h\f1] [\f3-p \f2port\f1] [\f3-u \f2userlist\f1]
[\f3-U \f2userlist\f1]
.SH DESCRIPTION
.IX "lsp"
.P
Show which IPv4 INET ports have processes bound to them in a LISTEN state.
.SH OPTIONS
.TP
\f3-t\f1
Shows only the process id and omits the header and other information.
This output is useful for passing to other programs, such as
.BR kill (1),
or for use in scripts.
.TP
\f3-x\f1
Extended argument listing. The default if UNIX95 is set in the environment.
.TP
\f3-n\f1
Do not resolve names.
.TP
\f3-h\f1
Do not print fully qualified hostnames (ignored when \f3-n\f1).
.TP
\f3\-p \f2port\f1
Restrict output to processes bound to \f2port\f1.
.TP
\f3\-u \f2userlist\f1
Restrict output to the processes whose effective user is one of the users
in \f2userlist\f1 - a comma separated list of user names or user ids.
.TP
\f3\-U \f2userlist\f1
As for \f3-u\f1 but the restriction is by real user id.
.SH AUTHOR
Simon Anthony(santhony@me.com)
.SH SEE ALSO
.BR lsof (1),
.BR netstat (1)
