.\" @(#)%W%
.fp 1 R
.fp 2 I
.fp 3 B
.fp 4 BI
.fp 5 R
.fp 6 I
.fp 7 B
.nr X
.TH TASdba 1 "07 Apr 2011" ""
.SH INTRODUCTION
DBAtools - an introduction to the DBAtools command utilities and application programs
.SH DESCRIPTION
.IX "DBAtools"
.P
\f3DBAtools\f1 is a package of utilities for assisting in the
administration of e-Business suite and Oracle database installations.
.SH COMMANDS
.TP
\f3\-b \f2blocksize\f1
Blocksize of the header block in 1K multiples.
.SH WARNINGS
.P
There is currently no way to determine whether a file is a control file.
.P
If BBED is not available in the \f5ORACLE_HOME\f1 \f3TASdba\f1 builds it and exits.
\f3TASdba\f1 must then be run again.
.SH AUTHOR
Simon Anthony (santhony@me.com)
.SH FILES
.TP 30
\f5$ORACLE_HOME/rdbms/lib/bbed\f1
block browser and editor 
.SH SEE ALSO
.BR make (1)
